Imports

In [1]:
import sys
sys.path.insert(0, "../src/")
import utils

import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
plt.style.use('ggplot')

import plotly
from urllib.request import urlopen
import json
import plotly.express as px
import plotly.graph_objects as go

Data manipulation

In [27]:
gdp = pd.read_csv('../data/GDP_PerCapita.csv')
gdp['Country/Territory'] = [con.replace("ï¿½","") for con in gdp['Country/Territory']]
gdp = gdp.replace({'United Arab Emirates': 'UAE'})
gdp

,Country/Territory,Subregion,Region,GDP Estimate in USD per capita as per IMF,Year as per IMF,GDP Estimate in USD per capita as per UN,Year as per UN,GDP Estimate in USD per capita as per World Bank,Year as per World Bank
0,Monaco,Western Europe,Europe,NaN,NaN,190532.0,2019,190513.0,2019.0
1,Liechtenstein,Western Europe,Europe,NaN,NaN,179258.0,2019,180367.0,2018.0
2,Luxembourg,Western Europe,Europe,131782.0,2021.0,115481.0,2019,115874.0,2020.0
3,Bermuda,Northern America,Americas,NaN,NaN,117768.0,2019,117098.0,2019.0
4,Cayman Islands,Caribbean,Americas,NaN,NaN,92692.0,2019,91393.0,2019.0
...,...,...,...,...,...,...,...,...,...
209,Malawi,Eastern Africa,Africa,432.0,2021.0,435.0,2019,625.0,2020.0
210,Mozambique,Eastern Africa,Africa,425.0,2021.0,504.0,2019,449.0,2020.0
211,Somalia,Eastern Africa,Africa,347.0,2021.0,105.0,2019,309.0,2020.0
212,South Sudan,Eastern Africa,Africa,315.0,2021.0,448.0,2019,1120.0,2015.0
213,Burundi,Eastern Africa,Africa,265.0,2021.0,260.0,2019,274.0,2020.0

In [25]:
vaccinationNumbers = pd.read_csv("../data/Global_COVID_Vaccination_Tracker.csv")
vaccinationNumbers = vaccinationNumbers.replace({'U.S.': 'United States','U.K.':'United Kingdom','Mainland China':'China',
                      'Republic of the Congo':'Congo'})
vaccinationNumbers

,Countries and regions,Doses administered,Enough for % of people,Percentage of population with 1+ dose,Percentage of population fully vaccinated,Daily rate of doses administered
0,Global Total,5.663213e+09,NaN,NaN,NaN,33380378.0
1,China,2.129833e+09,76.1,NaN,69.3,6454714.0
2,India,7.303371e+08,26.7,40.3,12.4,7616167.0
3,EU,5.469671e+08,61.6,66.0,61.5,1394444.0
4,United States,3.785697e+08,59.2,62.9,53.6,721844.0
...,...,...,...,...,...,...
202,Nauru,1.479000e+04,56.9,58.6,55.2,NaN
203,St. Helena,7.892000e+03,65.8,72.7,58.9,8.0
204,Falkland Islands,4.407000e+03,73.5,87.7,59.2,202.0
205,Montserrat,2.837000e+03,28.4,29.3,27.4,NaN
206,Eritrea,NaN,NaN,NaN,NaN,NaN

In [28]:
datamerge = pd.merge(gdp,vaccinationNumbers,left_on='Country/Territory',right_on='Countries and regions')
datamerge

,Country/Territory,Subregion,Region,GDP Estimate in USD per capita as per IMF,Year as per IMF,GDP Estimate in USD per capita as per UN,Year as per UN,GDP Estimate in USD per capita as per World Bank,Year as per World Bank,Countries and regions,Doses administered,Enough for % of people,Percentage of population with 1+ dose,Percentage of population fully vaccinated,Daily rate of doses administered
0,Monaco,Western Europe,Europe,NaN,NaN,190532.0,2019,190513.0,2019.0,Monaco,48691.0,62.4,67.0,57.8,270.0
1,Luxembourg,Western Europe,Europe,131782.0,2021.0,115481.0,2019,115874.0,2020.0,Luxembourg,771470.0,62.8,66.9,58.6,869.0
2,Bermuda,Northern America,Americas,NaN,NaN,117768.0,2019,117098.0,2019.0,Bermuda,85415.0,67.8,68.5,67.1,95.0
3,Cayman Islands,Caribbean,Americas,NaN,NaN,92692.0,2019,91393.0,2019.0,Cayman Islands,102399.0,78.8,80.7,76.9,196.0
4,Switzerland,Western Europe,Europe,94696.0,2021.0,85135.0,2019,86602.0,2020.0,Switzerland,9834906.0,57.5,59.9,52.9,23530.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,Madagascar,Eastern Africa,Africa,521.0,2021.0,523.0,2019,496.0,2020.0,Madagascar,283091.0,0.5,0.8,0.3,1230.0
188,Malawi,Eastern Africa,Africa,432.0,2021.0,435.0,2019,625.0,2020.0,Malawi,969645.0,2.4,3.5,2.1,5176.0
189,Mozambique,Eastern Africa,Africa,425.0,2021.0,504.0,2019,449.0,2020.0,Mozambique,2297842.0,3.7,5.3,2.1,84381.0
190,Somalia,Eastern Africa,Africa,347.0,2021.0,105.0,2019,309.0,2020.0,Somalia,310005.0,1.0,1.4,0.7,2980.0
191,South Sudan,Eastern Africa,Africa,315.0,2021.0,448.0,2019,1120.0,2015.0,South Sudan,59865.0,0.2,0.4,0.1,543.0

Choropleths

Bar charts

Correlations